include: ["_pages"]

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

remote_theme: "mmistakes/minimal-mistakes"

title: "<img alt='PREGO' src='https://evangelospafilis.github.io/prego_web_site/images/prego_cropped.png' style='border: 0; height:1em; padding-left:1em;'/>"
name                     : "Prego project : Process Environment Organism"
description              : "PREGO, text mining and data integration to elucidate ecosystem functioning: associating organisms and environments with biogeochemical and anthropogenic impact processes. Mining public knowledge to open novel doors in molecular ecology, microbiology and biodiversity.text mining, named entity recognition, environment ontology, environmental processes, microorganisms, microbial sequences, association extraction, confidence score, interactive network visualization, environmental microbiology, molecular ecology, biodiversity. IMBBC, HCMR, GSRT, HFRI."
defaults:
# _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
