include: ["_pages"]

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

remote_theme: "mmistakes/minimal-mistakes"

title: "<img alt='PREGO logo' src='https://evangelospafilis.github.io/prego_web_site/images/prego_cropped.png' style='border: 0; height:2em; padding-right:0.5em;'/>"
