include: ["_pages"]

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

remote_theme: "mmistakes/minimal-mistakes"

#title: "Home"
title: "<img alt='PREGO logo' src='{{ site.baseurl }}/images/prego.png' style='border: 0; height:2em; padding-right:0.5em;'/>"