include: ["_pages"]

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "contrast"
title: "PREGO: Process Environment Organism" 