include: ["_pages"]

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

remote_theme: "mmistakes/minimal-mistakes"

title: "<img alt='PREGO' src='https://evangelospafilis.github.io/prego_web_site/images/prego_cropped.png' style='border: 0; height:1em; padding-left:1em;'/>"

defaults:
# _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single

twitter:
  username               : &twitter "prego_project"
  
social:
  type                   : Organization
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/prego_project"
 
 # Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/prego_project"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/evangelospafilis/"
