include: ["_pages"]

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

remote_theme: "mmistakes/minimal-mistakes"

title: "<img alt='PREGO' src='https://evangelospafilis.github.io/prego_web_site/images/prego_cropped.png' style='border: 0; height:1em; padding-left:1em;'/>"

defaults:
# _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
